# Configurações Dynaconf para o projeto ONBOARDING

# Configurações padrão (podem ser sobrescritas por variáveis de ambiente)
SECRET_KEY = "django-insecure-change-me-in-production"
DEBUG = false
ALLOWED_HOSTS = []

# Database
DB_NAME = "onboarding"
DB_USER = "postgres"
DB_PASSWORD = ""
DB_HOST = "localhost"
DB_PORT = "5432"
DB_SSLMODE = "prefer"

# Cache
CACHE_URL = "redis://localhost:6379/1"

# Celery
CELERY_BROKER_URL = "redis://localhost:6379/0"
CELERY_RESULT_BACKEND = "redis://localhost:6379/0"

# Email
EMAIL_HOST = "localhost"
EMAIL_PORT = 587
EMAIL_USE_TLS = true
EMAIL_HOST_USER = ""
EMAIL_HOST_PASSWORD = ""
DEFAULT_FROM_EMAIL = "noreply@onboarding.com"

# Security
SESSION_COOKIE_AGE = 3600
CSRF_COOKIE_AGE = 3600

# File uploads
MAX_FILE_SIZE = 10485760  # 10MB

# API Rate limiting
API_RATE_LIMIT_ANON = "100/hour"
API_RATE_LIMIT_USER = "1000/hour"

# Monitoring
SENTRY_DSN = ""

# Version
VERSION = "1.0.0"

