site_name: ONBOARDING - Digital KYC Platform
site_description: Comprehensive documentation for the ONBOARDING digital KYC platform
site_author: ONBOARDING Team
site_url: https://onboarding-team.github.io/onboarding/

# Repository
repo_name: onboarding-team/onboarding
repo_url: https://github.com/onboarding-team/onboarding
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2025 ONBOARDING Team

# Configuration
theme:
  name: material
  language: en
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  font:
    text: Roboto
    code: Roboto Mono
  
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - toc.follow
    - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    - content.action.edit
    - content.action.view
  
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye

# Plugins
plugins:
  - search:
      lang: en
  - git-revision-date-localized:
      enable_creation_date: true
  - minify:
      minify_html: true
  - social
  - tags

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: onboarding-team
      repo: onboarding
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Extra
extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/onboarding-team/onboarding
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/onboarding/platform
  tags:
    Django: django
    API: api
    Frontend: frontend
    Security: security
    Testing: testing
    Deploy: deploy

# Extra CSS
extra_css:
  - stylesheets/extra.css

# Extra JavaScript
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Navigation
nav:
  - Home: index.md
  - Getting Started:
    - getting-started/index.md
    - Quick Start: getting-started/quick-start.md
    - Installation: getting-started/installation.md
    - Configuration: getting-started/configuration.md
    - First Steps: getting-started/first-steps.md
  
  - Architecture:
    - architecture/index.md
    - Overview: architecture/overview.md
    - Backend: architecture/backend.md
    - Frontend: architecture/frontend.md
    - Database: architecture/database.md
    - Security: architecture/security.md
    - Performance: architecture/performance.md
  
  - API Documentation:
    - api/index.md
    - Authentication: api/authentication.md
    - KYC Profiles: api/kyc-profiles.md
    - UBO Declarations: api/ubo-declarations.md
    - PEP Declarations: api/pep-declarations.md
    - Documents: api/documents.md
    - Error Handling: api/error-handling.md
  
  - Development:
    - development/index.md
    - Environment Setup: development/environment-setup.md
    - Code Style: development/code-style.md
    - Testing: development/testing.md
    - Contributing: development/contributing.md
    - Debugging: development/debugging.md
  
  - Deployment:
    - deployment/index.md
    - Railway.app: deployment/railway.md
    - Docker: deployment/docker.md
    - Environment Variables: deployment/environment-variables.md
    - Monitoring: deployment/monitoring.md
    - Troubleshooting: deployment/troubleshooting.md
  
  - User Guide:
    - user-guide/index.md
    - Admin Panel: user-guide/admin-panel.md
    - KYC Process: user-guide/kyc-process.md
    - Document Upload: user-guide/document-upload.md
    - Internationalization: user-guide/internationalization.md
  
  - Security:
    - security/index.md
    - Authentication: security/authentication.md
    - Authorization: security/authorization.md
    - Data Protection: security/data-protection.md
    - Compliance: security/compliance.md
    - Best Practices: security/best-practices.md
  
  - Reference:
    - reference/index.md
    - Configuration: reference/configuration.md
    - Commands: reference/commands.md
    - Models: reference/models.md
    - Utilities: reference/utilities.md
    - Changelog: reference/changelog.md

