site_name: BTS Global Bank - Digital KYC Platform
site_description: Secure, efficient, and compliant digital KYC platform for global banking solutions
site_author: BTS Development Team
site_url: https://docs.btsglobalbank.com

# Repository
repo_name: carlossilvatbh/onboarding-platform
repo_url: https://github.com/carlossilvatbh/onboarding-platform
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2025 BTS Global Bank. All rights reserved.

# Configuration
theme:
  name: material
  custom_dir: overrides
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Inter
    code: JetBrains Mono
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.action.edit
    - content.action.view
  logo: assets/bts-logo.png
  favicon: assets/favicon.ico

# Plugins
plugins:
  - search:
      lang: en
  - git-revision-date-localized:
      type: date
  - minify:
      minify_html: true

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: carlossilvatbh
      repo: onboarding-platform
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Home: index.md
  - Getting Started:
    - Overview: getting-started/index.md
    - Installation: getting-started/installation.md
    - Configuration: getting-started/configuration.md
    - Quick Start: getting-started/quick-start.md
  - Architecture:
    - Overview: architecture/index.md
    - Backend: architecture/backend.md
    - Frontend: architecture/frontend.md
    - Database: architecture/database.md
    - Security: architecture/security.md
  - API Reference:
    - Overview: api/index.md
    - Authentication: api/authentication.md
    - KYC Endpoints: api/kyc.md
    - UBO Endpoints: api/ubo.md
    - PEP Endpoints: api/pep.md
    - Documents: api/documents.md
  - Development:
    - Setup: development/setup.md
    - Testing: development/testing.md
    - Contributing: development/contributing.md
    - Code Style: development/code-style.md
  - Deployment:
    - Overview: deployment/index.md
    - Railway.app: deployment/railway.md
    - Docker: deployment/docker.md
    - Environment Variables: deployment/environment.md
  - User Guide:
    - Getting Started: user-guide/getting-started.md
    - KYC Process: user-guide/kyc-process.md
    - Document Upload: user-guide/document-upload.md
    - Troubleshooting: user-guide/troubleshooting.md
  - Security:
    - Overview: security/index.md
    - Authentication: security/authentication.md
    - Data Protection: security/data-protection.md
    - Compliance: security/compliance.md
  - Reference:
    - Configuration: reference/configuration.md
    - Error Codes: reference/error-codes.md
    - Changelog: reference/changelog.md
    - FAQ: reference/faq.md

# Extra
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/carlossilvatbh/onboarding-platform
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/bts-global-bank
    - icon: fontawesome/solid/globe
      link: https://btsglobalbank.com
  version:
    provider: mike
  analytics:
    provider: google
    property: G-XXXXXXXXXX

# Extra CSS
extra_css:
  - stylesheets/extra.css

# Extra JavaScript
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

